# https://gokarna-hugo.netlify.app/posts/theme-documentation-basics/
# https://gokarna-hugo.netlify.app/posts/theme-documentation-advanced/
# https://gohugo.io/documentation/

# Domain name
baseURL = "https://lunajay.co.uk/"

# Copyright notice (appended to footer)
copyright = "All rights reserved."

# Website language
defaultContentLanguage = "en"
languageCode = "en"

# Allow search engine crawlers
enableRobotsTXT = true

# Website title (e.g. author name)
title = "Luna Jay"

[params]
  # Resource URL for the site avatar (home page and header)
  avatarURL = "/images/avatar.webp"

  # Describe the avatar for screen readers
  avatarAltText = "Luna Jay"

  # Set the avatar's size: size-xs, size-s, size-m, size-l & size-xl
  avatarSize = "size-l"

  # Home page meta description
  description = "Content Creation, Marketing & Branding"

  # Body text font size
  fontSize = "20px"

  # Footer text (e.g. author name)
  footer = "Luna Jay"

  # SEO keywords
  metaKeywords = [ "branding", "content creation", "marketing" ]

  # Display back to top button when viewing below-the-fold content
  showBackToTopButton = true

  # Reduce the width of `_index.md` content when viewed on a large screen
  customHeadHTML = '''
      <style>
        @media only screen and (min-width: 820px)
        {
          .home-content { width: 66%; }
        }
      </style>
  '''

  # Display social media links on the home page
  #
  # `name` is derived from file names in `static/svg/icons`
  #
  # Gokarna includes some icons by default:
  # https://github.com/gokarna-theme/gokarna-hugo/tree/main/static/svg/icons
  #
  # Download more icons from Simple Icons: https://simpleicons.org/
  socialIcons = [
      {name = "instagram", url = "https://www.instagram.com/lunajaystudios/"},
      {name = "twitter", url = "https://twitter.com/lunajaystudios"},
      {name = "linkedin", url = "https://www.linkedin.com/in/lunajay/"},
      {name = "spotify", url = "https://open.spotify.com/show/7tJheHrHkcdwEYDc1OZsF0"},
      {name = "email", url = "mailto:hello@lunajay.co.uk"},
    ]

# Add internal and external links to navigation menu/bar

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<span data-feather='home'></span>"

  [[menu.main]]
    name = "Branding"
    url = "/branding/"
    weight = 2
    pre = "<span data-feather='image'></span>"

  [[menu.main]]
    name = "Contact"
    weight = 10
    url = "mailto:hello@lunajay.co.uk"
    pre = "<span data-feather='mail'></span>"

  [[menu.main]]
    name = "Instagram"
    url = "https://www.instagram.com/lunajaystudios/"
    weight = 20
    pre = "<span data-feather='instagram'></span>"
    [menu.main.params]
        newPage = true

  [[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/lunajaystudios"
    weight = 21
    pre = "<span data-feather='twitter'></span>"
    [menu.main.params]
        newPage = true

  [[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/lunajay/"
    weight = 22
    pre = "<span data-feather='linkedin'></span>"
    [menu.main.params]
        newPage = true

  [[menu.main]]
    name = "Spotify"
    url = "https://open.spotify.com/show/7tJheHrHkcdwEYDc1OZsF0"
    weight = 23
    pre = "<span data-feather='rss'></span>"
    [menu.main.params]
        newPage = true

# Reduce file size when building site by removing human-readable formatting
[minify]
    minifyOutput = true

# Import Hugo theme and third-party components
[module]
  [[module.imports]]
    path = "github.com/gokarna-theme/gokarna-hugo"
  [[module.imports]]
    path = "github.com/mfg92/hugo-shortcode-gallery"
